media: media
content:
- name: robots
  label: Robots
  type: collection
  path: content/robots
  filename:
    template: "{fields.year}Robot.md"
    field: false
  fields:
  - name: year
    label: Year
    type: number
  - name: robot_name
    label: Robot Name
    type: string
  - name: robot_image
    label: Robot Image
    type: image
  - name: game_logo
    label: Game Logo
    type: image
  - name: game_name
    label: Game Name
    type: string
  - name: game_video
    label: Game Video
    type: string
  - name: features
    label: Features
    type: object
    list: true
    fields:
      - name: item
        label: Item
        type: string
      - name: icon
        label: Icon
        type: string
  - name: specifications
    label: Specifications
    type: object
    list: true
    fields:
      - name: item
        label: Item
        type: string
  - name: capabilities
    label: Capabilities
    type: object
    list: true
    fields:
      - name: item
        label: Item
        type: string
  - name: competitions
    label: Competitions
    type: object
    list: true
    fields:
      - name: item
        label: Item
        type: string
  - name: links
    label: Links
    type: object
    list: true
    fields:
      - name: item
        label: Item
        type: string
      - name: link
        label: Link
        type: string
  - name: videos
    label: Videos
    type: object
    list: true
    fields:
      - name: item
        label: Item
        type: string
- name: awards
  label: Awards
  type: file
  path: content/awards.yml
  format: yaml
  list:
    collapsible:
      collapsed: false
      summary: "{fields.year}"
  fields: 
    - name: year
      type: number
    - name: awards
      type: string
      list: true
        
        
  
