language: ruby
# only run CI-builds on master branch
branches:
  only:
  - master
  - qa
rvm:
- 2.2.3
# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild
 - chmod u+x ./script/deploy
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false
addons:
  ssh_known_hosts: teambroncobots.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_58e0e546d520_key -iv $encrypted_58e0e546d520_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ./script/deploy
deploy:
  provider: script
  skip_cleanup: true
  script: echo "Deployed."
  on:
    branch: 
     - qa
     - master
